### ISSUE TITLE
Use Jetpack's Portfolio custom post type

### ISSUE THREAD

**Issue by emzo** [andrew-worsfold/tailor-portfolio#1]
Hi, I realise Jetpack is very much like Vegemite ([you either love it or hate it](https://www.quora.com/Why-do-people-either-love-or-hate-Marmite-and-Vegemite-Is-there-a-genetic-reason-or-just-personal-taste?srid=ijVs)), but just wondering if you've considered using its [Portfolio custom post type](https://jetpack.com/support/custom-content-types/#portfolios) rather than registering your own CPT for this extension?

**Comment by andrew-worsfold** [comment]
This is a good suggestion.  I am considering my options here and am leaning towards providing support for the Jetpack Portfolio custom post type within Tailor itself, given its popularity and broad adoption.

This would mean that a projects element would appear in the list of elements if Jetpack was enabled.  I intend to keep this Portfolio plugin separate as not everyone wants to have Jetpack enabled as well.

How does that sound?

**Comment by emzo** [comment]
Definitely makes sense, as on one hand, Jetpack does have a big install-base, and on the other, a lot of people think it's bloated. I'm all for Jetpack if I'm going to use a number of the modules it provides, but I wouldn't install it just for the Portfolio custom post type.

👍  Good call

**Comment by andrew-worsfold** [comment]
Done!  Check out the latest version of Tailor to see this in action 😄  Thanks again for the feedback!
